/*
0 - mandante
1 - adversario
2 - golsBotafogo
3 - golsAdversario
4 - campeonato
5 - data
6 - estádio
7 - técnico
8 - autorBotafogo
9 - autorAdversario
10 - escudo novo (se tiver)
*/

var jogos = [];

var jogo1 = [true, "Corinthians", 2, 0, "Campeonato Brasileiro", "2002-12-08", "Morumbi", "Emerson Leão", "-Alberto<br>-Renato", ""];
jogos.push(jogo1);
var jogo2 = [false, "Corinthians", 3, 2, "Campeonato Brasileiro", "2002-12-15", "Morumbi", "Emerson Leão", "-Elano<br>-Léo<br>-Robinho", "-Anderson<br>-Deivid"];
jogos.push(jogo2);
var jogo3 = [true, "Boca Juniors-ARG", 1, 3, "Copa Libertadores", "2003-07-02", "Morumbi", "Emerson Leão", "-Alex", "-Tévez<br>-Delgado<br>-Schiavi"];
jogos.push(jogo3);
var jogo4 = [false, "Palmeiras", 2, 1, "Campeonato Brasileiro", "2004-09-12", "Pacaembu", "Vanderlei Luxemburgo", "-Deivid<br>-Elano", "-Osmar"];
jogos.push(jogo4);
var jogo5 = [false, "São Paulo", 0, 1, "Campeonato Brasileiro", "2004-10-24", "Morumbi", "Vanderlei Luxemburgo", "", "-Grafite"];
jogos.push(jogo5);
var jogo6 = [false, "Juventus", 2, 1, "Campeonato Paulista", "2006-03-25", "Pacaembu", "Vanderlei Luxemburgo", "-Cléber Santana<br>-Reinaldo", "-Manu"];
jogos.push(jogo6);
var jogo7 = [true, "São Caetano", 2, 0, "Campeonato Paulista", "2007-05-06", "Morumbi", "Vanderlei Luxemburgo", "-Adaílton<br>-Morais", ""];
jogos.push(jogo7);
var jogo8 = [false, "Oeste", 2, 1, "Campeonato Paulista", "2009-03-07", "Pacaembu", "Vagner Mancini", "-Roni<br>-Madson", "-Dezinho"];
jogos.push(jogo8);
var jogo9 = [true, "Náutico", 3, 1, "Campeonato Brasileiro", "2009-11-07", "Pacaembu", "Vanderlei Luxemburgo", "-Kléber Pereira<br>-Neymar (2x)", "-Aílton"];
jogos.push(jogo9);
var jogo10 = [true, "Corinthians", 2, 1, "Campeonato Paulista", "2010-02-28", "Vila Belmiro", "Dorival Júnior", "-Neymar<br>-André", "-Dentinho"];
jogos.push(jogo10);
var jogo11 = [false, "Santo André", 3, 2, "Campeonato Paulista", "2010-04-25", "Pacaembu", "Dorival Júnior", "-André<br>-Wesley (2x)", "-Bruno César<br>-Rodriguinho"];
jogos.push(jogo11);
var jogo12 = [true, "Santo André", 2, 3, "Campeonato Paulista", "2010-05-02", "Pacaembu", "Dorival Júnior", "-Neymar (2x)", "-Nunes<br>-Alê<br>-Branquinho"];
jogos.push(jogo12);
var jogo13 = [true, "Deportivo Tachira-VEN", 3, 1, "Copa Libertadores", "2011-04-20", "Pacaembu", "Muricy Ramalho", "-Neymar<br>-Jonathan<br>-Danilo", "-Gerzon Chacón"];
jogos.push(jogo13);
var jogo14 = [true, "Once Caldas-COL", 1, 1, "Copa Libertadores", "2011-05-18", "Pacaembu", "Muricy Ramalho", "-Neymar", "-Rentería"];
jogos.push(jogo14);
var jogo15 = [true, "Cerro Porteño-PAR", 1, 0, "Copa Libertadores", "2011-05-25", "Pacaembu", "Muricy Ramalho", "-Edu Dracena", ""];
jogos.push(jogo15);
var jogo16 = [true, "Atlético-PR", 4, 1, "Campeonato Brasileiro", "2011-10-29", "Pacaembu", "Muricy Ramalho", "-Neymar (4x)", "-Guerrón"];
jogos.push(jogo16);
var jogo17 = [false, "Guarani", 3, 0, "Campeonato Paulista", "2012-05-06", "Morumbi", "Muricy Ramalho", "-Paulo Henrique Ganso<br>-Neymar (2x)", ""];
jogos.push(jogo17);
var jogo18 = [true, "Atlético-GO", 2, 2, "Campeonato Brasileiro", "2012-08-11", "Pacaembu", "Muricy Ramalho", "-Patito Rodríguez<br>-Miralles", "-Patric<br>-Wesley"];
jogos.push(jogo18);
var jogo19 = [true, "Portuguesa", 1, 3, "Campeonato Brasileiro", "2012-09-22", "Pacaembu", "Muricy Ramalho", "-André", "-Bruno Mineiro (2x)<br>-Léo Silva"];
jogos.push(jogo19);
var jogo20 = [true, "Grêmio Barueri", 4, 0, "Amistoso", "2013-01-16", "Pacaembu", "Muricy Ramalho", "-Neymar<br>-Galhardo<br>-Miralles<br>-Bill", ""];
jogos.push(jogo20);
var jogo21 = [true, "Paulista", 1, 3, "Campeonato Paulista", "2013-02-10", "Pacaembu", "Muricy Ramalho", "-Neymar", "-Marcelo Macedo<br>-Rodolfo Testoni<br>-Cassiano Bodini"];
jogos.push(jogo21);
var jogo184 = [true, "Portuguesa", 4, 1, "Campeonato Brasileiro", "2013-07-13", "Vila Belmiro", "Claudinei Oliveira", "-Neílton (2x)<br>-William José<br>-Giva", "-Bruno Moraes"];
jogos.push(jogo184);
var jogo22 = [true, "Ponte Preta", 2, 1, "Campeonato Brasileiro", "2013-10-12", "Pacaembu", "Claudinei Oliveira", "-Éverton Costa<br>-Montillo", "-Rafael Ratão"];
jogos.push(jogo22);
var jogo23 = [true, "Bahia", 3, 0, "Campeonato Brasileiro", "2013-11-14", "Pacaembu", "Claudinei Oliveira", "-Cícero (2x)<br>-Montillo", ""];
jogos.push(jogo23);
var jogo24 = [true, "Botafogo-SP", 5, 1, "Campeonato Paulista", "2014-02-01", "Vila Belmiro", "Oswaldo de Oliveira", "-Gabigol (2x)<br>-Emerson<br>-Guevânio<br>-Cícero", "-Hudson"];
jogos.push(jogo24);
var jogo25 = [true, "Palmeiras", 2, 0, "Campeonato Brasileiro", "2014-07-17", "Vila Belmiro", "Oswaldo de Oliveira", "-Bruno Uvini<br>-Alisson", ""];
jogos.push(jogo25);
var jogo26 = [true, "Goiás", 2, 0, "Campeonato Brasileiro", "2014-09-28", "Pacaembu", "Enderson Moreira", "-David Braz<br>-Geuvânio", ""];
jogos.push(jogo26);
var jogo27 = [true, "Botafogo", 5, 0, "Copa do Brasil", "2014-10-16", "Pacaembu", "Enderson Moreira", "-Gabigol<br>-David Braz (2x)<br>-Lucas Lima<br>-Geuvânio", ""];
jogos.push(jogo27);
var jogo28 = [true, "Ituano", 3, 0, "Campeonato Paulista", "2015-02-01", "Vila Belmiro", "Enderson Moreira", "-Chiquinho<br>-Geuvânio (2x)", ""];
jogos.push(jogo28);
var jogo29 = [false, "São Bernardo", 1, 0, "Campeonato Paulista", "2015-02-14", "Primeiro de Maio", "Enderson Moreira", "-David Braz", ""];
jogos.push(jogo29);
var jogo30 = [false, "Portuguesa", 3, 1, "Campeonato Paulista", "2015-02-22", "Pacaembu", "Enderson Moreira", "-Robinho (2x)<br>-Cicinho", "-Jean Mota"];
jogos.push(jogo30);
var jogo31 = [true, "Audax-SP", 1, 0, "Campeonato Paulista", "2015-03-21", "Vila Belmiro", "Marcelo Fernandes", "-Ricardo Oliveira", ""];
jogos.push(jogo31);
var jogo32 = [true, "Cruzeiro", 1, 0, "Campeonato Brasileiro", "2015-05-17", "Vila Belmiro", "Marcelo Fernandes", "-Geuvânio", ""];
jogos.push(jogo32);
var jogo33 = [true, "Sport", 2, 2, "Campeonato Brasileiro", "2015-05-31", "Vila Belmiro", "Marcelo Fernandes", "-Werley<br>-Robinho", "-Joelinton<br>-Samuel Xavier"];
jogos.push(jogo33);
var jogo34 = [true, "Coritiba", 3, 0, "Campeonato Brasileiro", "2015-08-08", "Vila Belmiro", "Dorival Júnior", "-Geuvânio<br>-Ivan (Gol Contra)<br>-Ricardo Oliveira", ""];
jogos.push(jogo34);
var jogo35 = [false, "Corinthians", 0, 2, "Campeonato Brasileiro", "2015-09-20", "Arena Corinthians", "Dorival Júnior", "", "-Jadson (2x)"];
jogos.push(jogo35);
var jogo36 = [true, "Figueirense", 3, 2, "Copa do Brasil", "2015-10-01", "Pacaembu", "Dorival Júnior", "-Neto Berola<br>-Gabigol<br>-Marquinhos Gabriel", "-Carlos Alberto<br>-Bruno Alves"];
jogos.push(jogo36);
var jogo37 = [true, "Fluminense", 3, 1, "Campeonato Brasileiro", "2015-10-04", "Vila Belmiro", "Dorival Júnior", "-Lucas Lima<br>-Marquinhos Gabriel<br>-Neto Berola", "-Robert"];
jogos.push(jogo37);
var jogo38 = [true, "São Bernardo", 1, 1, "Campeonato Paulista", "2016-01-30", "Vila Belmiro", "Dorival Júnior", "-Gabigol", "-Luciano Castán"];
jogos.push(jogo38);
var jogo39 = [true, "Mogi Mirim", 4, 1, "Campeonato Paulista", "2016-02-25", "Pacaembu", "Dorival Júnior", "-Bruno Costa (Gol Contra)<br>-Lucas Lima<br>-Joel (2x)", "Wendel"];
jogos.push(jogo39);
var jogo40 = [true, "Corinthians", 2, 0, "Campeonato Paulista", "2016-03-06", "Vila Belmiro", "Dorival Júnior", "-Ricardo Oliveira (2x)", ""];
jogos.push(jogo40);
var jogo41 = [true, "Água Santa", 1, 0, "Campeonato Paulista", "2016-03-12", "Pacaembu", "Dorival Júnior", "-Eli Sabiá", ""];
jogos.push(jogo41);
var jogo42 = [true, "São Bento", 2, 0, "Campeonato Paulista", "2016-04-16", "Vila Belmiro", "Dorival Júnior", "-Vitor Bueno (2x)", ""];
jogos.push(jogo42);
var jogo43 = [true, "Palmeiras", 2, 2, "Campeonato Paulista", "2016-04-24", "Vila Belmiro", "Dorival Júnior", "-Gabigol (2x)\r\n<br>\r\n<br>\r\nPênaltis (3):<br>\r\n-David Braz<br>-Zeca<br>-Victor Ferraz", "-Rafael Marques (2x)\r\n<br>\r\n<br>\r\nPênaltis (2):<br>\r\n-Cleiton Xavier<br>-Jean"];
jogos.push(jogo43);
var jogo44 = [true, "Audax-SP", 1, 0, "Campeonato Paulista", "2016-05-08", "Vila Belmiro", "Dorival Júnior", "-Ricardo Oliveira", ""];
jogos.push(jogo44);
var jogo45 = [true, "Coritiba", 2, 1, "Campeonato Brasileiro", "2016-05-22", "Vila Belmiro", "Dorival Júnior", "-Vitor Bueno<br>-Renato", "-Kléber"];
jogos.push(jogo45);
var jogo46 = [true, "Internacional", 0, 1, "Campeonato Brasileiro", "2016-05-29", "Vila Belmiro", "Dorival Júnior", "", "-Aylon"];
jogos.push(jogo46);
var jogo47 = [true, "Botafogo", 3, 0, "Campeonato Brasileiro", "2016-06-05", "Pacaembu", "Dorival Júnior", "-Vitor Bueno<br>-Paulinho<br>-Bruno Silva (Gol Contra)", ""];
jogos.push(jogo47);
var jogo48 = [true, "Sport", 2, 0, "Campeonato Brasileiro", "2016-06-15", "Vila Belmiro", "Oswaldo de Oliveira", "-Gabigol<br>-Vitor Bueno", ""];
jogos.push(jogo48);
var jogo49 = [true, "São Paulo", 3, 0, "Campeonato Brasileiro", "2016-06-26", "Pacaembu", "Dorival Júnior", "-Vitor Bueno<br>-Rodrigão<br>-Lucas Lima", ""];
jogos.push(jogo49);
var jogo50 = [true, "Chapecoense", 3, 0, "Campeonato Brasileiro", "2016-07-03", "Vila Belmiro", "Dorival Júnior", "-Rodrigão<br>-Copete<br>-Yuri", ""];
jogos.push(jogo50);
var jogo51 = [true, "Ponte Preta", 3, 1, "Campeonato Brasileiro", "2016-07-16", "Vila Belmiro", "Dorival Júnior", "-Victor Ferraz<br>-Vitor Bueno<br>-Gabigol", "-Roger"];
jogos.push(jogo51);
var jogo52 = [true, "Cruzeiro", 2, 0, "Campeonato Brasileiro", "2016-07-31", "Vila Belmiro", "Dorival Júnior", "-Vitor Bueno<br>-Lucas (Gol Contra)", ""];
jogos.push(jogo52);
var jogo53 = [false, "Coritiba", 1, 2, "Campeonato Brasileiro", "2016-08-21", "Couto Pereira", "Dorival Júnior", "-Ricardo Oliveira", "-Kléber<br>-Iago Dias"];
jogos.push(jogo53);
var jogo54 = [true, "Vasco", 3, 1, "Copa do Brasil", "2016-08-24", "Vila Belmiro", "Dorival Júnior", "-Renato<br>-Ricardo Oliveira<br>-Lucas Lima", "-Éder Luís"];
jogos.push(jogo54);
var jogo55 = [true, "Corinthians", 2, 1, "Campeonato Brasileiro", "2016-09-11", "Vila Belmiro", "Dorival Júnior", "-Vitor Bueno<br>-Renato", "-Marlone"];
jogos.push(jogo55);
var jogo56 = [true, "Santa Cruz", 3, 2, "Campeonato Brasileiro", "2016-09-18", "Pacaembu", "Dorival Júnior", "-Copete<br>-Jean Mota<br>-Vitor Bueno", "-Keno (2x)"];
jogos.push(jogo56);
var jogo57 = [true, "Benfica-POR", 1, 1, "Amistoso", "2016-10-08", "Vila Belmiro", "Dorival Júnior", "-Fábian Noguera", "-Salvio"];
jogos.push(jogo57);
var jogo58 = [false, "São Paulo", 1, 0, "Campeonato Brasileiro", "2016-10-13", "Pacaembu", "Dorival Júnior", "-Copete", ""];
jogos.push(jogo58);
var jogo59 = [true, "Grêmio", 1, 1, "Campeonato Brasileiro", "2016-10-16", "Vila Belmiro", "Dorival Júnior", "-Fábian Noguera", "-Éverton"];
jogos.push(jogo59);
var jogo60 = [true, "Palmeiras", 1, 0, "Campeonato Brasileiro", "2016-10-29", "Vila Belmiro", "Dorival Júnior", "-Copete", ""];
jogos.push(jogo60);
var jogo61 = [false, "Ponte Preta", 2, 1, "Campeonato Brasileiro", "2016-11-06", "Moisés Lucarelli", "Dorival Júnior", "-Ricardo Oliveira<br>-Copete", "-William Pottker"];
jogos.push(jogo61);
var jogo62 = [true, "Floresta-CE", 1, 0, "Copinha", "2017-01-04", "Arena Barueri", "Marcos Soares", "-Giovane", ""];
jogos.push(jogo62);
var jogo63 = [false, "Audax-SP", 1, 1, "Copinha", "2017-01-08", "Arena Barueri", "Marcos Soares", "-André Anderson", "-Wesley"];
jogos.push(jogo63);
var jogo64 = [true, "Kenitra-MAR", 5, 1, "Amistoso", "2017-01-28", "Pacaembu", "Dorival Júnior", "-Rodrigão<br>-Vitor Bueno (2x)<br>-Vladimir Hernández<br>-Thiago Ribeiro", "-Hamza"];
jogos.push(jogo64);
var jogo65 = [true, "Linense", 6, 2, "Campeonato Paulista", "2017-02-03", "Vila Belmiro", "Dorival Júnior", "-Rodrigão (2x)<br>-Lucas Lima<br>-Arthur Gomes<br>-Vitor Bueno<br>-Thiago Ribeiro", "-Thiago Santos<br>-Gabrielzinho"];
jogos.push(jogo65);
var jogo66 = [false, "Red Bull Brasil", 3, 2, "Campeonato Paulista", "2017-02-12", "Pacaembu", "Dorival Júnior", "-Vitor Bueno<br>-Rodrigão<br>-Kayke", "-Misael<br>-Nixon"];
jogos.push(jogo66);
var jogo67 = [true, "Ferroviária", 0, 1, "Campeonato Paulista", "2017-02-18", "Vila Belmiro", "Dorival Júnior", "", "-Leandro Amaro"];
jogos.push(jogo67);
var jogo68 = [false, "São Bernardo", 4, 1, "Campeonato Paulista", "2017-03-12", "Primeiro de Maio", "Dorival Júnior", "-Bruno Henrique (3x)<br>-Rafael Longuine", "-Geandro"];
jogos.push(jogo68);
var jogo69 = [true, "The Strongest-BOL", 2, 0, "Copa Libertadores", "2017-03-16", "Vila Belmiro", "Dorival Júnior", "-Ricardo Oliveira<br>-Renato", ""];
jogos.push(jogo69);
var jogo70 = [false, "Santo André", 1, 0, "Campeonato Paulista", "2017-03-25", "Bruno José Daniel", "Dorival Júnior", "-Copete", ""];
jogos.push(jogo70);
var jogo71 = [true, "Ponte Preta", 1, 0, "Campeonato Paulista", "2017-04-10", "Pacaembu", "Dorival Júnior", "-David Braz\r\n<br><br>\r\nPênaltis (4):<br>\r\n-Kayke<br>\r\n-Jean Mota<br>\r\n-Copete<br>\r\n-Lucas Lima", "<br><br>\r\nPênaltis (5):<br>\r\n-Ravanelli<br>\r\n-Yago<br>\r\n-Clayson<br>\r\n-Jadson<br>\r\n-William Pottker"];
jogos.push(jogo71);
var jogo72 = [true, "Independiente Santa Fé-COL", 3, 2, "Copa Libertadores", "2017-05-04", "Pacaembu", "Dorival Júnior", "-Ricardo Oliveira<br>-Vitor Bueno<br>-Lucas Veríssimo", "-Arango<br>-Perlaza"];
jogos.push(jogo72);
var jogo73 = [false, "Fluminense", 2, 3, "Campeonato Brasileiro", "2017-05-14", "Maracanã", "Dorival Júnior", "-Victor Ferraz<br>-Vladimir Hernández", "-Henrique Dourado (2x)<br>-Sornoza"];
jogos.push(jogo73);
var jogo74 = [true, "Coritiba", 1, 0, "Campeonato Brasileiro", "2017-05-20", "Vila Belmiro", "Dorival Júnior", "-David Braz", ""];
jogos.push(jogo74);
var jogo75 = [true, "Sporting Cristal-PER", 4, 0, "Copa Libertadores", "2017-05-23", "Vila Belmiro", "Dorival Júnior", "-David Braz (2x)<br>-Ricardo Oliveira<br>-Vitor Bueno", ""];
jogos.push(jogo75);
var jogo76 = [true, "Cruzeiro", 0, 1, "Campeonato Brasileiro", "2017-05-28", "Vila Belmiro", "Dorival Júnior", "", "-Thiago Neves"];
jogos.push(jogo76);
var jogo77 = [true, "Botafogo", 1, 0, "Campeonato Brasileiro", "2017-06-07", "Pacaembu", "Dorival Júnior", "-Victor Ferraz", ""];
jogos.push(jogo77);
var jogo78 = [false, "Atlético-PR", 2, 0, "Campeonato Brasileiro", "2017-06-11", "Arena da Baixada", "Elano", "-Kayke (2x)", ""];
jogos.push(jogo78);
var jogo79 = [true, "Palmeiras", 1, 0, "Campeonato Brasileiro", "2017-06-14", "Vila Belmiro", "Levir Culpi", "-Kayke", ""];
jogos.push(jogo79);
var jogo80 = [true, "Ponte Preta", 0, 0, "Campeonato Brasileiro", "2017-06-17", "Pacaembu", "Levir Culpi", "", ""];
jogos.push(jogo80);
var jogo81 = [true, "São Paulo", 3, 2, "Campeonato Brasileiro", "2017-07-09", "Vila Belmiro", "Levir Culpi", "-Copete (3x)", "-Shaylon<br>-Arboleda"];
jogos.push(jogo81);
var jogo82 = [true, "Chapecoense", 1, 0, "Campeonato Brasileiro", "2017-07-19", "Vila Belmiro", "Levir Culpi", "-Vecchio", ""];
jogos.push(jogo82);
var jogo83 = [true, "Bahia", 3, 0, "Campeonato Brasileiro", "2017-07-23", "Pacaembu", "Levir Culpi", "-Bruno Henrique (3x)", ""];
jogos.push(jogo83);
var jogo84 = [true, "Flamengo", 4, 2, "Copa do Brasil", "2017-07-26", "Vila Belmiro", "Levir Culpi", "-Bruno Henrique<br>-Copete (2x)<br>-Victor Ferraz", "-Berrío<br>-Guerrero"];
jogos.push(jogo84);
var jogo85 = [true, "Flamengo", 3, 2, "Campeonato Brasileiro", "2017-08-02", "Pacaembu", "Levir Culpi", "-Bruno Henrique<br>-Alisson<br>-Ricardo Oliveira", "-Éverton Ribeiro<br>-Felipe Vizeu"];
jogos.push(jogo85);
var jogo86 = [false, "Avaí", 0, 0, "Campeonato Brasileiro", "2017-08-06", "da Ressacada", "Levir Culpi", "", ""];
jogos.push(jogo86);
var jogo87 = [true, "Atlético-PR", 1, 0, "Copa Libertadores", "2017-08-10", "Vila Belmiro", "Levir Culpi", "-Bruno Henrique", ""];
jogos.push(jogo87);
var jogo88 = [true, "Fluminense", 0, 0, "Campeonato Brasileiro", "2017-08-14", "Pacaembu", "Levir Culpi", "", ""];
jogos.push(jogo88);
var jogo89 = [false, "Cruzeiro", 1, 1, "Campeonato Brasileiro", "2017-08-27", "Mineirão", "Levir Culpi", "-Bruno Henrique", "-Rafinha"];
jogos.push(jogo89);
var jogo90 = [true, "Corinthians", 2, 0, "Campeonato Brasileiro", "2017-09-10", "Vila Belmiro", "Levir Culpi", "-Lucas Lima<br>-Ricardo Oliveira", ""];
jogos.push(jogo90);
var jogo91 = [false, "Botafogo", 0, 2, "Campeonato Brasileiro", "2017-09-16", "Nilton Santos", "Levir Culpi", "", "-Rodrigo Lindoso<br>-Guilherme"];
jogos.push(jogo91);
var jogo92 = [true, "Atlético-PR", 1, 0, "Campeonato Brasileiro", "2017-09-23", "Vila Belmiro", "Levir Culpi", "-Bruno Henrique", ""];
jogos.push(jogo92);
var jogo93 = [true, "Vitória", 2, 2, "Campeonato Brasileiro", "2017-10-16", "Pacaembu", "Levir Culpi", "-Jean Mota<br>-Ramon", "-David<br>-Wallace Reis"];
jogos.push(jogo93);
var jogo94 = [true, "Atlético-GO", 1, 0, "Campeonato Brasileiro", "2017-10-22", "Vila Belmiro", "Levir Culpi", "-Ricardo Oliveira", ""];
jogos.push(jogo94);
var jogo95 = [true, "Atlético-MG", 3, 1, "Campeonato Brasileiro", "2017-11-04", "Vila Belmiro", "Levir Culpi", "-Arthur Gomes<br>-David Braz<br>-Ricardo Oliveira", "-Fred"];
jogos.push(jogo95);
var jogo96 = [true, "Grêmio", 1, 0, "Campeonato Brasileiro", "2017-11-19", "Vila Belmiro", "Elano", "-Copete", ""];
jogos.push(jogo96);
var jogo97 = [false, "Flamengo", 2, 1, "Campeonato Brasileiro", "2017-11-26", "Ilha do Urubu", "Elano", "-Bruno Henrique<br>-Arthur Gomes", "-Lucas Paquetá"];
jogos.push(jogo97);
var jogo98 = [true, "Avaí", 1, 1, "Campeonato Brasileiro", "2017-12-03", "Vila Belmiro", "Elano", "-Copete", "-Pedro Castro"];
jogos.push(jogo98);
var jogo99 = [true, "Internacional", 1, 1, "Brasileirão de Aspirantes", "2017-12-10", "Vila Belmiro", "Kleiton Lima", "-Diego Cardoso", "-Joanderson"];
jogos.push(jogo99);
var jogo100 = [true, "São Caetano", 2, 0, "Campeonato Paulista", "2018-02-14", "Vila Belmiro", "Jair Ventura", "-Lucas Veríssimo<br>-Gabigol", ""];
jogos.push(jogo100);
var jogo101 = [true, "Santo André", 2, 0, "Campeonato Paulista", "2018-02-25", "Vila Belmiro", "Jair Ventura", "-Gabigol<br>-Eduardo Sasha", ""];
jogos.push(jogo101);
var jogo102 = [true, "Corinthians", 1, 1, "Campeonato Paulista", "2018-03-04", "Pacaembu", "Jair Ventura", "-Diogo Vitor", "-Renê Junior"];
jogos.push(jogo102);
var jogo103 = [true, "São Bento", 1, 3, "Campeonato Paulista", "2018-03-11", "Vila Belmiro", "Jair Ventura", "-Arthur Gomes", "-Marcelo Cordeiro<br>-Lúcio Flávio<br>-Fábio Bahia"];
jogos.push(jogo103);
var jogo104 = [true, "Nacional-URU", 3, 1, "Copa Libertadores", "2018-03-15", "Pacaembu", "Jair Ventura", "-Eduardo Sasha (2x)<br>-Rodrygo", "-Oliva"];
jogos.push(jogo104);
var jogo105 = [true, "Botafogo-SP", 0, 0, "Campeonato Paulista", "2018-03-21", "Vila Belmiro", "Jair Ventura", "<br><br>\r\nPênaltis (3):<br>-Gabigol<br>-Diogo Vitor<br>-Arthur Gomes", "<br>\r\nPênaltis (1):<br>-Jheymy"];
jogos.push(jogo105);
var jogo106 = [true, "Palmeiras", 0, 1, "Campeonato Paulista", "2018-03-24", "Pacaembu", "Jair Ventura", "", "-Willian"];
jogos.push(jogo106);
var jogo107 = [true, "Ceará", 2, 0, "Campeonato Brasileiro", "2018-04-14", "Pacaembu", "Jair Ventura", "-Pio (Gol Contra)<br>-Rodrygo", ""];
jogos.push(jogo107);
var jogo108 = [true, "Estudiantes-ARG", 2, 0, "Copa Libertadores", "2018-04-24", "Vila Belmiro", "Jair Ventura", "-Gabigol<br>-Lucas Veríssimo", ""];
jogos.push(jogo108);
var jogo183 = [false, "Nacional-URU", 0, 1, "Copa Libertadores", "2018-05-01", "Gran Parque Central", "Jair Ventura", "", "-Barcia"];
jogos.push(jogo183);
var jogo109 = [true, "Luverdense", 5, 1, "Copa do Brasil", "2018-05-10", "Vila Belmiro", "Jair Ventura", "-Gustavo Henrique<br>-Gabigol (3x)<br>-Yuri Alberto", "-Itaqui"];
jogos.push(jogo109);
var jogo110 = [true, "Paraná", 3, 1, "Campeonato Brasileiro", "2018-05-13", "Vila Belmiro", "Jair Ventura", "-Gabigol (2x)<br>-Rodrygo", "-Silvinho"];
jogos.push(jogo110);
var jogo111 = [true, "Real Garcilaso-PER", 0, 0, "Copa Libertadores", "2018-05-24", "Vila Belmiro", "Jair Ventura", "", ""];
jogos.push(jogo111);
var jogo112 = [true, "Cruzeiro", 0, 1, "Campeonato Brasileiro", "2018-05-27", "Pacaembu", "Jair Ventura", "", "-Bruno Silva"];
jogos.push(jogo112);
var jogo113 = [true, "Vitória", 5, 2, "Campeonato Brasileiro", "2018-06-03", "Vila Belmiro", "Jair Ventura", "-Renato<br>-Gabigol<br>Rodrygo(3x)", "-Neílton<br>-Ramon"];
jogos.push(jogo113);
var jogo114 = [true, "Internacional", 1, 2, "Campeonato Brasileiro", "2018-06-10", "Vila Belmiro", "Jair Ventura", "-Gabigol", "-Leandro Damião<br>-Victor Cuesta"];
jogos.push(jogo114);
var jogo115 = [true, "Palmeiras", 1, 1, "Campeonato Brasileiro", "2018-07-19", "Pacaembu", "Jair Ventura", "-Gustavo Henrique", "-Lucas Lima"];
jogos.push(jogo115);
var jogo116 = [true, "Flamengo", 1, 1, "Campeonato Brasileiro", "2018-07-25", "Vila Belmiro", "Serginho Chulapa", "-Rodrygo", "-Éverton Ribeiro"];
jogos.push(jogo116);
var jogo117 = [true, "América-MG", 0, 1, "Campeonato Brasileiro", "2018-07-29", "Vila Belmiro", "Serginho Chulapa", "", "-Ruy"];
jogos.push(jogo117);
var jogo118 = [true, "Cruzeiro", 0, 1, "Copa do Brasil", "2018-08-01", "Vila Belmiro", "Cuca", "", "-Raniel"];
jogos.push(jogo118);
var jogo119 = [false, "Botafogo", 0, 0, "Campeonato Brasileiro", "2018-08-04", "Nilton Santos", "Cuca", "", ""];
jogos.push(jogo119);
var jogo120 = [true, "Sport", 3, 0, "Campeonato Brasileiro", "2018-08-18", "Vila Belmiro", "Cuca", "-Eduardo Sasha<br>-Rodrygo<br>-Victor Ferraz", ""];
jogos.push(jogo120);
var jogo121 = [false, "Independiente-ARG", 0, 0, "Copa Libertadores", "2018-08-21", "Libertadores de América", "Cuca", "", ""];
jogos.push(jogo121);
var jogo122 = [true, "Bahia", 2, 0, "Campeonato Brasileiro", "2018-08-25", "Vila Belmiro", "Cuca", "-Derlis González<br>-Gabigol", ""];
jogos.push(jogo122);
var jogo123 = [true, "Independiente-ARG", 0, 0, "Copa Libertadores", "2018-08-28", "Pacaembu", "Cuca", "", ""];
jogos.push(jogo123);
var jogo124 = [false, "Vasco", 3, 0, "Campeonato Brasileiro", "2018-09-01", "Maracanã", "Cuca", "-Gabigol (3x)", ""];
jogos.push(jogo124);
var jogo125 = [true, "Grêmio", 0, 0, "Campeonato Brasileiro", "2018-09-06", "Pacaembu", "Cuca", "", ""];
jogos.push(jogo125);
var jogo126 = [true, "São Paulo", 0, 0, "Campeonato Brasileiro", "2018-09-16", "Vila Belmiro", "Cuca", "", ""];
jogos.push(jogo126);
var jogo127 = [true, "Atlético-PR", 1, 0, "Campeonato Brasileiro", "2018-09-30", "Vila Belmiro", "Cuca", "-Carlos Sánchez", ""];
jogos.push(jogo127);
var jogo128 = [true, "Corinthians", 1, 0, "Campeonato Brasileiro", "2018-10-13", "Pacaembu", "Cuca", "-Gabigol", ""];
jogos.push(jogo128);
var jogo129 = [true, "Fluminense", 3, 0, "Campeonato Brasileiro", "2018-10-27", "Vila Belmiro", "Cuca", "-Gabigol<br>-Carlos Sánchez<br>-Victor Ferraz", ""];
jogos.push(jogo129);
var jogo130 = [true, "Chapecoense", 0, 1, "Campeonato Brasileiro", "2018-11-12", "Pacaembu", "Cuca", "", "-Leandro Pereira"];
jogos.push(jogo130);
var jogo131 = [false, "Flamengo", 0, 1, "Campeonato Brasileiro", "2018-11-15", "Maracanã", "Cuca", "", "-Henrique Dourado"];
jogos.push(jogo131);
var jogo132 = [false, "América-MG", 1, 2, "Campeonato Brasileiro", "2018-11-18", "Arena Independência", "Cuca", "-Gabigol", "-Rafael Moura<br>-Matheusinho"];
jogos.push(jogo132);
var jogo133 = [true, "Botafogo", 1, 1, "Campeonato Brasileiro", "2018-11-21", "Vila Belmiro", "Cuca", "-Rodrygo", "-Brenner"];
jogos.push(jogo133);
var jogo134 = [true, "Atlético-MG", 3, 2, "Campeonato Brasileiro", "2018-11-24", "Vila Belmiro", "Cuca", "-Felippe Cardoso<br>-Gabigol<br>-Carlos Sánchez", "-Ricardo Oliveira (2x)"];
jogos.push(jogo134);
var jogo135 = [false, "Sport", 1, 2, "Campeonato Brasileiro", "2018-12-02", "Ilha do Retiro", "Cuca", "-Rodrygo", "-Rogério<br>-Hernane"];
jogos.push(jogo135);
var jogo136 = [true, "Ferroviária", 1, 0, "Campeonato Paulista", "2019-01-19", "Vila Belmiro", "Jorge Sampaoli", "-Jean Mota", ""];
jogos.push(jogo136);
var jogo137 = [true, "São Paulo", 2, 0, "Campeonato Paulista", "2019-01-27", "Pacaembu", "Jorge Sampaoli", "-Luiz Felipe<br>-Derlis González", ""];
jogos.push(jogo137);
var jogo138 = [false, "Ituano", 1, 5, "Campeonato Paulista", "2019-02-03", "Municipal Doutor Novelli Júnior", "Jorge Sampaoli", "-Jean Mota", "-Marcos Serato<br>-Morato (2x)<br>-Léo Santos<br>-Jonas"];
jogos.push(jogo138);
var jogo139 = [true, "Mirassol", 1, 0, "Campeonato Paulista", "2019-02-09", "Pacaembu", "Jorge Sampaoli", "-Jean Mota", ""];
jogos.push(jogo139);
var jogo140 = [false, "River Plate-URU", 0, 0, "Copa Sul-Americana", "2019-02-12", "Luis Franzini", "Jorge Sampaoli", "", ""];
jogos.push(jogo140);
var jogo141 = [true, "Guarani", 3, 0, "Campeonato Paulista", "2019-02-18", "Pacaembu", "Jorge Sampaoli", "-Rodrygo<br>-Jean Mota (2x)", ""];
jogos.push(jogo141);
var jogo142 = [true, "Oeste", 3, 2, "Campeonato Paulista", "2019-03-02", "Pacaembu", "Jorge Sampaoli", "-Betinho (Gol Contra)<br>-Derlis González<br>-Victor Ferraz", "-Bruno Lopes<br>-Matheus Jesus"];
jogos.push(jogo142);
var jogo143 = [true, "América-RN", 4, 0, "Copa do Brasil", "2019-03-09", "Pacaembu", "Jorge Sampaoli", "-Rodrygo<br>-Aguilar<br>-Jean Mota<br>Derlis González", ""];
jogos.push(jogo143);
var jogo144 = [true, "Novorizontino", 0, 1, "Campeonato Paulista", "2019-03-15", "Pacaembu", "Jorge Sampaoli", "", "-Murilo Henrique"];
jogos.push(jogo144);
var jogo145 = [true, "Red Bull Brasil", 2, 0, "Campeonato Paulista", "2019-03-23", "Pacaembu", "Jorge Sampaoli", "-Diego Pituca<br>-Carlos Sánchez", ""];
jogos.push(jogo145);
var jogo146 = [true, "Corinthians", 1, 0, "Campeonato Paulista", "2019-04-08", "Pacaembu", "Jorge Sampaoli", "-Gustavo Henrique\r\n<br><br>\r\nPênaltis (6):<br>\r\n-Rodrygo<br>\r\n-Soteldo<br>\r\n-Carlos Sánchez<br>\r\n-Derlis González<br>\r\n-Diego Pituca<br>\r\n-Alison", "<br><br>\r\nPênaltis (7):<br>\r\n-Vagner Love<br>\r\n-Ramiro<br>\r\n-Júnior Urso<br>\r\n-Fagner<br>\r\n-Sornoza<br>\r\n-Danilo Avelar<br>\r\n-Henrique"];
jogos.push(jogo146);
var jogo147 = [true, "Vasco", 2, 0, "Copa do Brasil", "2019-04-17", "Vila Belmiro", "Jorge Sampaoli", "-Rodrygo<br>-Jean Mota", ""];
jogos.push(jogo147);
var jogo148 = [false, "Grêmio", 2, 1, "Campeonato Brasileiro", "2019-04-28", "Arena do Grêmio", "Jorge Sampaoli", "-Eduardo Sasha<br>-Felipe Jonathan", "-Éverton"];
jogos.push(jogo148);
var jogo149 = [true, "Vasco", 3, 0, "Campeonato Brasileiro", "2019-05-12", "Pacaembu", "Jorge Sampaoli", "-Diego Pituca<br>-Rodrygo<br>-Soteldo", ""];
jogos.push(jogo149);
var jogo150 = [true, "Internacional", 0, 0, "Campeonato Brasileiro", "2019-05-26", "Vila Belmiro", "Jorge Sampaoli", "", ""];
jogos.push(jogo150);
var jogo151 = [false, "Ceará", 1, 0, "Campeonato Brasileiro", "2019-06-02", "Castelão", "Jorge Sampaoli", "-Eduardo Sasha", ""];
jogos.push(jogo151);
var jogo152 = [false, "Juventus", 8, 1, "Campeonato Paulista (Feminino)", "2019-06-08", "Conde Rodolfo Crespi (Rua Javari)", "Emily Lima", "-Maria Dias<br>-Maria Alves<br>-Sandrinha<br>-Sochor<br>-Glaucia<br>-Katielle<br>-Ketlen (2x)", "-Dani"];
jogos.push(jogo152);
var jogo153 = [true, "Atlético-MG", 3, 1, "Campeonato Brasileiro", "2019-06-09", "Vila Belmiro", "Jorge Sampaoli", "-Eduardo Sasha<br>-Jean Mota<br>-Carlos Sánchez", "-Alerrandro"];
jogos.push(jogo153);
var jogo154 = [true, "Corinthians", 1, 0, "Campeonato Brasileiro", "2019-06-12", "Vila Belmiro", "Jorge Sampaoli", "-Eduardo Sasha", ""];
jogos.push(jogo154);
var jogo155 = [false, "Bahia", 1, 0, "Campeonato Brasileiro", "2019-07-13", "Pituaçu", "Jorge Sampaoli", "-Carlos Sánchez", ""];
jogos.push(jogo155);
var jogo156 = [false, "Botafogo", 1, 0, "Campeonato Brasileiro", "2019-07-21", "Nilton Santos", "Jorge Sampaoli", "-Marinho", ""];
jogos.push(jogo156);
var jogo157 = [true, "Avaí", 3, 1, "Campeonato Brasileiro", "2019-07-28", "Vila Belmiro", "Jorge Sampaoli", "-Felipe Jonathan<br>-Carlos Sánchez<br>-Derlis González", "-João Paulo"];
jogos.push(jogo157);
var jogo158 = [true, "Goiás", 6, 1, "Campeonato Brasileiro", "2019-08-04", "Vila Belmiro", "Jorge Sampaoli", "-Lucas Veríssimo<br>-Soteldo (2x)<br>-Carlos Sánchez<br>-Gustavo Henrique<br>-Eduardo Sasha", "-Kayke"];
jogos.push(jogo158);
var jogo159 = [false, "Cruzeiro", 0, 2, "Campeonato Brasileiro", "2019-08-18", "Mineirão", "Jorge Sampaoli", "", "-Fred<br>-Thiago Neves"];
jogos.push(jogo159);
var jogo160 = [true, "Fortaleza", 3, 3, "Campeonato Brasileiro", "2019-08-25", "Vila Belmiro", "Jorge Sampaoli", "-Jorge<br>-Eduardo Sasha<br>-Marinho", "-Wellington Paulista (2x)<br>-Tinga"];
jogos.push(jogo160);
var jogo161 = [true, "Athletico-PR", 1, 1, "Campeonato Brasileiro", "2019-09-08", "Vila Belmiro", "Jorge Sampaoli", "-Carlos Sánchez", "-Braian Romero"];
jogos.push(jogo161);
var jogo162 = [false, "Flamengo", 0, 1, "Campeonato Brasileiro", "2019-09-14", "Maracanã", "Jorge Sampaoli", "", "-Gabriel"];
jogos.push(jogo162);
var jogo163 = [true, "São Paulo", 2, 2, "Campeonato Paulista (Feminino)", "2019-09-21", "Pacaembu", "Guilherme Giudice", "-Sole Jaimes<br>-Ketlen", "-Thaís<br>-Natane"];
jogos.push(jogo163);
var jogo164 = [true, "Grêmio", 0, 3, "Campeonato Brasileiro", "2019-09-21", "Vila Belmiro", "Jorge Sampaoli", "", "-Luan<br>-Pepê<br>-Éverton"];
jogos.push(jogo164);
var jogo165 = [true, "CSA", 2, 0, "Campeonato Brasileiro", "2019-09-29", "Vila Belmiro", "Jorge Sampaoli", "-Carlos Sánchez<br>-Eduardo Sasha", ""];
jogos.push(jogo165);
var jogo166 = [false, "Vasco", 1, 0, "Campeonato Brasileiro", "2019-10-05", "São Januário", "Jorge Sampaoli", "-Tailson", ""];
jogos.push(jogo166);
var jogo167 = [true, "Palmeiras", 2, 0, "Campeonato Brasileiro", "2019-10-09", "Vila Belmiro", "Jorge Sampaoli", "-Gustavo Henrique<br>-Marinho", ""];
jogos.push(jogo167);
var jogo168 = [false, "Internacional", 0, 0, "Campeonato Brasileiro", "2019-10-13", "Beira-Rio", "Jorge Sampaoli", "", ""];
jogos.push(jogo168);
var jogo169 = [false, "Atlético-MG", 0, 2, "Campeonato Brasileiro", "2019-10-20", "Arena Independência", "Jorge Sampaoli", "", "-Leonardo Silva<br>-Luan"];
jogos.push(jogo169);
var jogo170 = [true, "Botafogo", 4, 1, "Campeonato Brasileiro", "2019-11-03", "Vila Belmiro", "Jorge Sampaoli", "-Eduardo Sasha<br>-Marinho<br>-Soteldo (2x)", "-Igor Cássio"];
jogos.push(jogo170);
var jogo171 = [false, "Goiás", 3, 0, "Campeonato Brasileiro", "2019-11-09", "Serra Dourada", "Jorge Sampaoli", "-Soteldo (2x)<br>-Marinho", ""];
jogos.push(jogo171);
var jogo172 = [true, "São Paulo", 1, 1, "Campeonato Brasileiro", "2019-11-16", "Vila Belmiro", "Jorge Sampaoli", "-Carlos Sánchez", "-Daniel Alves"];
jogos.push(jogo172);
var jogo173 = [true, "Cruzeiro", 4, 1, "Campeonato Brasileiro", "2019-11-23", "Vila Belmiro", "Jorge Sampaoli", "-Eduardo Sasha<br>-Marinho<br>-Soteldo<br>-Diego Pituca", "-Orejuela"];
jogos.push(jogo173);
var jogo174 = [true, "Chapecoense", 2, 0, "Campeonato Brasileiro", "2019-12-01", "Vila Belmiro", "Jorge Sampaoli", "-Lucas Veríssimo<br>-Evandro", ""];
jogos.push(jogo174);
var jogo175 = [true, "Flamengo", 4, 0, "Campeonato Brasileiro", "2019-12-08", "Vila Belmiro", "Jorge Sampaoli", "-Marinho<br>-Carlos Sánchez (2x)<br>-Eduardo Sasha", ""];
jogos.push(jogo175);
var jogo176 = [true, "Red Bull Bragantino", 0, 0, "Campeonato Paulista", "2020-01-23", "Vila Belmiro", "Jesualdo Ferreira", "", ""];
jogos.push(jogo176);
var jogo177 = [true, "Botafogo-SP", 2, 0, "Campeonato Paulista", "2020-02-10", "Vila Belmiro", "Jesualdo Ferreira", "-Carlos Sánchez<br>-Eduardo Sasha", ""];
jogos.push(jogo177);
var jogo178 = [false, "Ferroviária", 0, 0, "Campeonato Paulista", "2020-02-16", "Fonte Luminosa", "Jesualdo Ferreira", "", ""];
jogos.push(jogo178);
var jogo179 = [false, "Ituano", 0, 2, "Campeonato Paulista", "2020-02-22", "Municipal Doutor Novelli Júnior", "Jesualdo Ferreira", "", "-Yago<br>-Corrêa"];
jogos.push(jogo179);
var jogo180 = [true, "Palmeiras", 0, 0, "Campeonato Paulista", "2020-02-29", "Pacaembu", "Jesualdo Ferreira", "", ""];
jogos.push(jogo180);
var jogo181 = [false, "Defensa y Justicia-ARG", 2, 1, "Copa Libertadores", "2020-03-03", "Norberto 'Tito' Tomaghello", "Jesualdo Ferreira", "-Jobson<br>-Kaio Jorge", "-Juan Rodríguez"];
jogos.push(jogo181);
var jogo182 = [true, "Mirassol", 3, 1, "Campeonato Paulista", "2020-03-07", "Vila Belmiro", "Jesualdo Ferreira", "-Yuri Alberto<br>-Diego Pituca<br>-Eduardo Sasha", "-Rafael Silva"];
jogos.push(jogo182);
var jogo183 = [false, "Palmeiras", 0, 1, "Copa Libertadores", "2021-01-30", "Maracanã", "Cuca", "", "-Breno Lopes"];
jogos.push(jogo183);
var jogo22082021 = [true, "Internacional", 2, 2, "Campeonato Brasileiro", "2021-08-22", "Vila Belmiro", "Fernando Diniz", "-Gabriel Pirani<br>-Madson", "-Gabriel Mercado<br>-Yuri Alberto"];
jogos.push(jogo22082021);
var jogo10102021 = [true, "Grêmio", 1, 0, "Campeonato Brasileiro", "2021-10-10", "Vila Belmiro", "Fábio Carille", "-Wagner Leonardo", ""];
jogos.push(jogo10102021);
var jogo23102021 = [true, "América-MG", 0, 2, "Campeonato Brasileiro", "2021-10-10", "Vila Belmiro", "Fábio Carille", "", "-Ademir<br>-Alê"];
jogos.push(jogo23102021);