/*
0 - mandante
1 - adversario
2 - golsBotafogo
3 - golsAdversario
4 - campeonato
5 - data
6 - estádio
7 - técnico
8 - autorBotafogo
9 - autorAdversario
10 - escudo novo (se tiver)
*/

var jogos = [];

var jogo20021208 = ["Santos", "Corinthians", 2, 0, "Campeonato Brasileiro", "2002-12-08", "Morumbi", "Emerson Leão", ["Alberto","Renato"], [""]];
jogos.push(jogo20021208);
var jogo20021215 = ["Corinthians", "Santos", 2, 3, "Campeonato Brasileiro", "2002-12-15", "Morumbi", "Emerson Leão", ["Elano","Léo","Robinho"], ["Anderson","Deivid"]];
jogos.push(jogo20021215);
var jogo20030702 = ["Santos", "Boca Juniors-ARG", 1, 3, "Copa Libertadores", "2003-07-02", "Morumbi", "Emerson Leão", ["Alex"], ["Tévez","Delgado","Schiavi"]];
jogos.push(jogo20030702);
var jogo20040912 = ["Palmeiras", "Santos", 1, 2, "Campeonato Brasileiro", "2004-09-12", "Pacaembu", "Vanderlei Luxemburgo", ["Deivid","Elano"], ["Osmar"]];
jogos.push(jogo20040912);
var jogo20041024 = ["São Paulo", "Santos", 1, 0, "Campeonato Brasileiro", "2004-10-24", "Morumbi", "Vanderlei Luxemburgo", [""], ["Grafite"]];
jogos.push(jogo20041024);
var jogo20060325 = ["Juventus", "Santos", 1, 2, "Campeonato Paulista", "2006-03-25", "Pacaembu", "Vanderlei Luxemburgo", ["Cléber Santana","Reinaldo"], ["Manu"]];
jogos.push(jogo20060325);
var jogo20070506 = ["Santos", "São Caetano", 2, 0, "Campeonato Paulista", "2007-05-06", "Morumbi", "Vanderlei Luxemburgo", ["Adaílton","Morais"], [""]];
jogos.push(jogo20070506);
var jogo20090307 = ["Oeste", "Santos", 1, 2, "Campeonato Paulista", "2009-03-07", "Pacaembu", "Vagner Mancini", ["Roni","Madson"], ["Dezinho"]];
jogos.push(jogo20090307);
var jogo20091107 = ["Santos", "Náutico", 3, 1, "Campeonato Brasileiro", "2009-11-07", "Pacaembu", "Vanderlei Luxemburgo", ["Kléber Pereira","Neymar (2x)"], ["Aílton"]];
jogos.push(jogo20091107);
var jogo10 = ["Santos", "Corinthians", 2, 1, "Campeonato Paulista", "2010-02-28", "Vila Belmiro", "Dorival Júnior", ["Neymar","André"], ["Dentinho"]];
jogos.push(jogo10);
var jogo11 = ["Santo André", "Santos", 2, 3, "Campeonato Paulista", "2010-04-25", "Pacaembu", "Dorival Júnior", ["André","Wesley (2x)"], ["Bruno César","Rodriguinho"]];
jogos.push(jogo11);
var jogo12 = ["Santos", "Santo André", 2, 3, "Campeonato Paulista", "2010-05-02", "Pacaembu", "Dorival Júnior", ["Neymar (2x)"], ["Nunes","Alê","Branquinho"]];
jogos.push(jogo12);
var jogo13 = ["Santos", "Deportivo Tachira-VEN", 3, 1, "Copa Libertadores", "2011-04-20", "Pacaembu", "Muricy Ramalho", ["Neymar","Jonathan","Danilo"], ["Gerzon Chacón"]];
jogos.push(jogo13);
var jogo14 = ["Santos", "Once Caldas-COL", 1, 1, "Copa Libertadores", "2011-05-18", "Pacaembu", "Muricy Ramalho", ["Neymar"], ["Rentería"]];
jogos.push(jogo14);
var jogo15 = ["Santos", "Cerro Porteño-PAR", 1, 0, "Copa Libertadores", "2011-05-25", "Pacaembu", "Muricy Ramalho", ["Edu Dracena"], [""]];
jogos.push(jogo15);
var jogo16 = ["Santos", "Atlético-PR", 4, 1, "Campeonato Brasileiro", "2011-10-29", "Pacaembu", "Muricy Ramalho", ["Neymar (4x)"], ["Guerrón"]];
jogos.push(jogo16);
var jogo17 = ["Guarani", "Santos", 0, 3, "Campeonato Paulista", "2012-05-06", "Morumbi", "Muricy Ramalho", ["Paulo Henrique Ganso","Neymar (2x)"], [""]];
jogos.push(jogo17);
var jogo18 = ["Santos", "Atlético-GO", 2, 2, "Campeonato Brasileiro", "2012-08-11", "Pacaembu", "Muricy Ramalho", ["Patito Rodríguez","Miralles"], ["Patric","Wesley"]];
jogos.push(jogo18);
var jogo19 = ["Santos", "Portuguesa", 1, 3, "Campeonato Brasileiro", "2012-09-22", "Pacaembu", "Muricy Ramalho", ["André"], ["Bruno Mineiro (2x)","Léo Silva"]];
jogos.push(jogo19);
var jogo20 = ["Santos", "Grêmio Barueri", 4, 0, "Amistoso", "2013-01-16", "Pacaembu", "Muricy Ramalho", ["Neymar","Galhardo","Miralles","Bill"], [""]];
jogos.push(jogo20);
var jogo21 = ["Santos", "Paulista", 1, 3, "Campeonato Paulista", "2013-02-10", "Pacaembu", "Muricy Ramalho", ["Neymar"], ["Marcelo Macedo","Rodolfo Testoni","Cassiano Bodini"]];
jogos.push(jogo21);
var jogo184 = ["Santos", "Portuguesa", 4, 1, "Campeonato Brasileiro", "2013-07-13", "Vila Belmiro", "Claudinei Oliveira", ["Neílton (2x)","William José","Giva"], ["Bruno Moraes"]];
jogos.push(jogo184);
var jogo22 = ["Santos", "Ponte Preta", 2, 1, "Campeonato Brasileiro", "2013-10-12", "Pacaembu", "Claudinei Oliveira", ["Éverton Costa","Montillo"], ["Rafael Ratão"]];
jogos.push(jogo22);
var jogo23 = ["Santos", "Bahia", 3, 0, "Campeonato Brasileiro", "2013-11-14", "Pacaembu", "Claudinei Oliveira", ["Cícero (2x)","Montillo"], [""]];
jogos.push(jogo23);
var jogo24 = ["Santos", "Botafogo-SP", 5, 1, "Campeonato Paulista", "2014-02-01", "Vila Belmiro", "Oswaldo de Oliveira", ["Gabigol (2x)","Emerson","Guevânio","Cícero"], ["Hudson"]];
jogos.push(jogo24);
var jogo25 = ["Santos", "Palmeiras", 2, 0, "Campeonato Brasileiro", "2014-07-17", "Vila Belmiro", "Oswaldo de Oliveira", ["Bruno Uvini","Alisson"], [""]];
jogos.push(jogo25);
var jogo26 = ["Santos", "Goiás", 2, 0, "Campeonato Brasileiro", "2014-09-28", "Pacaembu", "Enderson Moreira", ["David Braz","Geuvânio"], [""]];
jogos.push(jogo26);
var jogo27 = ["Santos", "Botafogo", 5, 0, "Copa do Brasil", "2014-10-16", "Pacaembu", "Enderson Moreira", ["Gabigol","David Braz (2x)","Lucas Lima","Geuvânio"], [""]];
jogos.push(jogo27);
var jogo28 = ["Santos", "Ituano", 3, 0, "Campeonato Paulista", "2015-02-01", "Vila Belmiro", "Enderson Moreira", ["Chiquinho","Geuvânio (2x)"], [""]];
jogos.push(jogo28);
var jogo29 = ["São Bernardo", "Santos", 0, 1, "Campeonato Paulista", "2015-02-14", "Primeiro de Maio", "Enderson Moreira", ["David Braz"], [""]];
jogos.push(jogo29);
var jogo30 = ["Portuguesa", "Santos", 1, 3, "Campeonato Paulista", "2015-02-22", "Pacaembu", "Enderson Moreira", ["Robinho (2x)","Cicinho"], ["Jean Mota"]];
jogos.push(jogo30);
var jogo31 = ["Santos", "Audax-SP", 1, 0, "Campeonato Paulista", "2015-03-21", "Vila Belmiro", "Marcelo Fernandes", ["Ricardo Oliveira"], [""]];
jogos.push(jogo31);
var jogo32 = ["Santos", "Cruzeiro", 1, 0, "Campeonato Brasileiro", "2015-05-17", "Vila Belmiro", "Marcelo Fernandes", ["Geuvânio"], [""]];
jogos.push(jogo32);
var jogo33 = ["Santos", "Sport", 2, 2, "Campeonato Brasileiro", "2015-05-31", "Vila Belmiro", "Marcelo Fernandes", ["Werley","Robinho"], ["Joelinton","Samuel Xavier"]];
jogos.push(jogo33);
var jogo34 = ["Santos", "Coritiba", 3, 0, "Campeonato Brasileiro", "2015-08-08", "Vila Belmiro", "Dorival Júnior", ["Geuvânio","Ivan (GC)","Ricardo Oliveira"], [""]];
jogos.push(jogo34);
var jogo35 = ["Corinthians", "Santos", 2, 0, "Campeonato Brasileiro", "2015-09-20", "Arena Corinthians", "Dorival Júnior", [""], ["Jadson (2x)"]];
jogos.push(jogo35);
var jogo36 = ["Santos", "Figueirense", 3, 2, "Copa do Brasil", "2015-10-01", "Pacaembu", "Dorival Júnior", ["Neto Berola","Gabigol","Marquinhos Gabriel"], ["Carlos Alberto","Bruno Alves"]];
jogos.push(jogo36);
var jogo37 = ["Santos", "Fluminense", 3, 1, "Campeonato Brasileiro", "2015-10-04", "Vila Belmiro", "Dorival Júnior", ["Lucas Lima","Marquinhos Gabriel","Neto Berola"], ["Robert"]];
jogos.push(jogo37);
var jogo38 = ["Santos", "São Bernardo", 1, 1, "Campeonato Paulista", "2016-01-30", "Vila Belmiro", "Dorival Júnior", ["Gabigol"], ["Luciano Castán"]];
jogos.push(jogo38);
var jogo39 = ["Santos", "Mogi Mirim", 4, 1, "Campeonato Paulista", "2016-02-25", "Pacaembu", "Dorival Júnior", ["Bruno Costa (GC)","Lucas Lima","Joel (2x)"], ["Wendel"]];
jogos.push(jogo39);
var jogo40 = ["Santos", "Corinthians", 2, 0, "Campeonato Paulista", "2016-03-06", "Vila Belmiro", "Dorival Júnior", ["Ricardo Oliveira (2x)"], [""]];
jogos.push(jogo40);
var jogo41 = ["Santos", "Água Santa", 1, 0, "Campeonato Paulista", "2016-03-12", "Pacaembu", "Dorival Júnior", ["Eli Sabiá"], [""]];
jogos.push(jogo41);
var jogo42 = ["Santos", "São Bento", 2, 0, "Campeonato Paulista", "2016-04-16", "Vila Belmiro", "Dorival Júnior", ["Vitor Bueno (2x)"], [""]];
jogos.push(jogo42);
var jogo43 = ["Santos", "Palmeiras", 2, 2, "Campeonato Paulista", "2016-04-24", "Vila Belmiro", "Dorival Júnior", ["Gabigol (2x)","","Pênaltis: (3)","David Braz","Zeca","Victor Ferraz"], ["Rafael Marques (2x)","","Pênaltis: (2)","Cleiton Xavier","Jean"]];
jogos.push(jogo43);
var jogo44 = ["Santos", "Audax-SP", 1, 0, "Campeonato Paulista", "2016-05-08", "Vila Belmiro", "Dorival Júnior", ["Ricardo Oliveira"], [""]];
jogos.push(jogo44);
var jogo45 = ["Santos", "Coritiba", 2, 1, "Campeonato Brasileiro", "2016-05-22", "Vila Belmiro", "Dorival Júnior", ["Vitor Bueno","Renato"], ["Kléber"]];
jogos.push(jogo45);
var jogo46 = ["Santos", "Internacional", 0, 1, "Campeonato Brasileiro", "2016-05-29", "Vila Belmiro", "Dorival Júnior", [""], ["Aylon"]];
jogos.push(jogo46);
var jogo47 = ["Santos", "Botafogo", 3, 0, "Campeonato Brasileiro", "2016-06-05", "Pacaembu", "Dorival Júnior", ["Vitor Bueno","Paulinho","Bruno Silva (GC)"], [""]];
jogos.push(jogo47);
var jogo48 = ["Santos", "Sport", 2, 0, "Campeonato Brasileiro", "2016-06-15", "Vila Belmiro", "Oswaldo de Oliveira", ["Gabigol","Vitor Bueno"], [""]];
jogos.push(jogo48);
var jogo49 = ["Santos", "São Paulo", 3, 0, "Campeonato Brasileiro", "2016-06-26", "Pacaembu", "Dorival Júnior", ["Vitor Bueno","Rodrigão","Lucas Lima"], [""]];
jogos.push(jogo49);
var jogo50 = ["Santos", "Chapecoense", 3, 0, "Campeonato Brasileiro", "2016-07-03", "Vila Belmiro", "Dorival Júnior", ["Rodrigão","Copete","Yuri"], [""]];
jogos.push(jogo50);
var jogo51 = ["Santos", "Ponte Preta", 3, 1, "Campeonato Brasileiro", "2016-07-16", "Vila Belmiro", "Dorival Júnior", ["Victor Ferraz","Vitor Bueno","Gabigol"], ["Roger"]];
jogos.push(jogo51);
var jogo52 = ["Santos", "Cruzeiro", 2, 0, "Campeonato Brasileiro", "2016-07-31", "Vila Belmiro", "Dorival Júnior", ["Vitor Bueno","Lucas (GC)"], [""]];
jogos.push(jogo52);
var jogo53 = ["Coritiba", "Santos", 2, 1, "Campeonato Brasileiro", "2016-08-21", "Couto Pereira", "Dorival Júnior", ["Ricardo Oliveira"], ["Kléber","Iago Dias"]];
jogos.push(jogo53);
var jogo54 = ["Santos", "Vasco", 3, 1, "Copa do Brasil", "2016-08-24", "Vila Belmiro", "Dorival Júnior", ["Renato","Ricardo Oliveira","Lucas Lima"], ["Éder Luís"]];
jogos.push(jogo54);
var jogo55 = ["Santos", "Corinthians", 2, 1, "Campeonato Brasileiro", "2016-09-11", "Vila Belmiro", "Dorival Júnior", ["Vitor Bueno","Renato"], ["Marlone"]];
jogos.push(jogo55);
var jogo56 = ["Santos", "Santa Cruz", 3, 2, "Campeonato Brasileiro", "2016-09-18", "Pacaembu", "Dorival Júnior", ["Copete","Jean Mota","Vitor Bueno"], ["Keno (2x)"]];
jogos.push(jogo56);
var jogo57 = ["Santos", "Benfica-POR", 1, 1, "Amistoso", "2016-10-08", "Vila Belmiro", "Dorival Júnior", ["Fábian Noguera"], ["Salvio"]];
jogos.push(jogo57);
var jogo58 = ["São Paulo", "Santos", 0, 1, "Campeonato Brasileiro", "2016-10-13", "Pacaembu", "Dorival Júnior", ["Copete"], [""]];
jogos.push(jogo58);
var jogo59 = ["Santos", "Grêmio", 1, 1, "Campeonato Brasileiro", "2016-10-16", "Vila Belmiro", "Dorival Júnior", ["Fábian Noguera"], ["Éverton"]];
jogos.push(jogo59);
var jogo60 = ["Santos", "Palmeiras", 1, 0, "Campeonato Brasileiro", "2016-10-29", "Vila Belmiro", "Dorival Júnior", ["Copete"], [""]];
jogos.push(jogo60);
var jogo61 = ["Ponte Preta", "Santos", 1, 2, "Campeonato Brasileiro", "2016-11-06", "Moisés Lucarelli", "Dorival Júnior", ["Ricardo Oliveira","Copete"], ["William Pottker"]];
jogos.push(jogo61);
var jogo62 = ["Santos", "Floresta-CE", 1, 0, "Copinha", "2017-01-04", "Arena Barueri", "Marcos Soares", ["Giovane"], [""]];
jogos.push(jogo62);
var jogo63 = ["Audax-SP", "Santos", 1, 1, "Copinha", "2017-01-08", "Arena Barueri", "Marcos Soares", ["André Anderson"], ["Wesley"]];
jogos.push(jogo63);
var jogo64 = ["Santos", "Kenitra-MAR", 5, 1, "Amistoso", "2017-01-28", "Pacaembu", "Dorival Júnior", ["Rodrigão","Vitor Bueno (2x)","Vladimir Hernández","Thiago Ribeiro"], ["Hamza"]];
jogos.push(jogo64);
var jogo65 = ["Santos", "Linense", 6, 2, "Campeonato Paulista", "2017-02-03", "Vila Belmiro", "Dorival Júnior", ["Rodrigão (2x)","Lucas Lima","Arthur Gomes","Vitor Bueno","Thiago Ribeiro"], ["Thiago Santos","Gabrielzinho"]];
jogos.push(jogo65);
var jogo66 = ["Red Bull Brasil", "Santos", 2, 3, "Campeonato Paulista", "2017-02-12", "Pacaembu", "Dorival Júnior", ["Vitor Bueno","Rodrigão","Kayke"], ["Misael","Nixon"]];
jogos.push(jogo66);
var jogo67 = ["Santos", "Ferroviária", 0, 1, "Campeonato Paulista", "2017-02-18", "Vila Belmiro", "Dorival Júnior", [""], ["Leandro Amaro"]];
jogos.push(jogo67);
var jogo68 = ["São Bernardo", "Santos", 1, 4, "Campeonato Paulista", "2017-03-12", "Primeiro de Maio", "Dorival Júnior", ["Bruno Henrique (3x)","Rafael Longuine"], ["Geandro"]];
jogos.push(jogo68);
var jogo69 = ["Santos", "The Strongest-BOL", 2, 0, "Copa Libertadores", "2017-03-16", "Vila Belmiro", "Dorival Júnior", ["Ricardo Oliveira","Renato"], [""]];
jogos.push(jogo69);
var jogo70 = ["Santo André", "Santos", 0, 1, "Campeonato Paulista", "2017-03-25", "Bruno José Daniel", "Dorival Júnior", ["Copete"], [""]];
jogos.push(jogo70);
var jogo71 = ["Santos", "Ponte Preta", 1, 0, "Campeonato Paulista", "2017-04-10", "Pacaembu", "Dorival Júnior", ["David Braz","","Pênaltis: (4)","Kayke","Jean Mota","Copete","Lucas Lima"], ["","","Pênaltis: (5)","Ravanelli","Yago","Clayson","Jadson","William Pottker"]];
jogos.push(jogo71);
var jogo72 = ["Santos", "Independiente Santa Fé-COL", 3, 2, "Copa Libertadores", "2017-05-04", "Pacaembu", "Dorival Júnior", ["Ricardo Oliveira","Vitor Bueno","Lucas Veríssimo"], ["Arango","Perlaza"]];
jogos.push(jogo72);
var jogo73 = ["Fluminense", "Santos", 3, 2, "Campeonato Brasileiro", "2017-05-14", "Maracanã", "Dorival Júnior", ["Victor Ferraz","Vladimir Hernández"], ["Henrique Dourado (2x)","Sornoza"]];
jogos.push(jogo73);
var jogo74 = ["Santos", "Coritiba", 1, 0, "Campeonato Brasileiro", "2017-05-20", "Vila Belmiro", "Dorival Júnior", ["David Braz"], [""]];
jogos.push(jogo74);
var jogo75 = ["Santos", "Sporting Cristal-PER", 4, 0, "Copa Libertadores", "2017-05-23", "Vila Belmiro", "Dorival Júnior", ["David Braz (2x)","Ricardo Oliveira","Vitor Bueno"], [""]];
jogos.push(jogo75);
var jogo76 = ["Santos", "Cruzeiro", 0, 1, "Campeonato Brasileiro", "2017-05-28", "Vila Belmiro", "Dorival Júnior", [""], ["Thiago Neves"]];
jogos.push(jogo76);
var jogo77 = ["Santos", "Botafogo", 1, 0, "Campeonato Brasileiro", "2017-06-07", "Pacaembu", "Dorival Júnior", ["Victor Ferraz"], [""]];
jogos.push(jogo77);
var jogo78 = ["Atlético-PR", "Santos", 0, 2, "Campeonato Brasileiro", "2017-06-11", "Arena da Baixada", "Elano", ["Kayke (2x)"], [""]];
jogos.push(jogo78);
var jogo79 = ["Santos", "Palmeiras", 1, 0, "Campeonato Brasileiro", "2017-06-14", "Vila Belmiro", "Levir Culpi", ["Kayke"], [""]];
jogos.push(jogo79);
var jogo80 = ["Santos", "Ponte Preta", 0, 0, "Campeonato Brasileiro", "2017-06-17", "Pacaembu", "Levir Culpi", [""], [""]];
jogos.push(jogo80);
var jogo81 = ["Santos", "São Paulo", 3, 2, "Campeonato Brasileiro", "2017-07-09", "Vila Belmiro", "Levir Culpi", ["Copete (3x)"], ["Shaylon","Arboleda"]];
jogos.push(jogo81);
var jogo82 = ["Santos", "Chapecoense", 1, 0, "Campeonato Brasileiro", "2017-07-19", "Vila Belmiro", "Levir Culpi", ["Vecchio"], [""]];
jogos.push(jogo82);
var jogo83 = ["Santos", "Bahia", 3, 0, "Campeonato Brasileiro", "2017-07-23", "Pacaembu", "Levir Culpi", ["Bruno Henrique (3x)"], [""]];
jogos.push(jogo83);
var jogo84 = ["Santos", "Flamengo", 4, 2, "Copa do Brasil", "2017-07-26", "Vila Belmiro", "Levir Culpi", ["Bruno Henrique","Copete (2x)","Victor Ferraz"], ["Berrío","Guerrero"]];
jogos.push(jogo84);
var jogo85 = ["Santos", "Flamengo", 3, 2, "Campeonato Brasileiro", "2017-08-02", "Pacaembu", "Levir Culpi", ["Bruno Henrique","Alisson","Ricardo Oliveira"], ["Éverton Ribeiro","Felipe Vizeu"]];
jogos.push(jogo85);
var jogo86 = ["Avaí", "Santos", 0, 0, "Campeonato Brasileiro", "2017-08-06", "da Ressacada", "Levir Culpi", [""], [""]];
jogos.push(jogo86);
var jogo87 = ["Santos", "Atlético-PR", 1, 0, "Copa Libertadores", "2017-08-10", "Vila Belmiro", "Levir Culpi", ["Bruno Henrique"], [""]];
jogos.push(jogo87);
var jogo88 = ["Santos", "Fluminense", 0, 0, "Campeonato Brasileiro", "2017-08-14", "Pacaembu", "Levir Culpi", [""], [""]];
jogos.push(jogo88);
var jogo89 = ["Cruzeiro", "Santos", 1, 1, "Campeonato Brasileiro", "2017-08-27", "Mineirão", "Levir Culpi", ["Bruno Henrique"], ["Rafinha"]];
jogos.push(jogo89);
var jogo90 = ["Santos", "Corinthians", 2, 0, "Campeonato Brasileiro", "2017-09-10", "Vila Belmiro", "Levir Culpi", ["Lucas Lima","Ricardo Oliveira"], [""]];
jogos.push(jogo90);
var jogo91 = ["Botafogo", "Santos", 2, 0, "Campeonato Brasileiro", "2017-09-16", "Nilton Santos", "Levir Culpi", [""], ["Rodrigo Lindoso","Guilherme"]];
jogos.push(jogo91);
var jogo92 = ["Santos", "Atlético-PR", 1, 0, "Campeonato Brasileiro", "2017-09-23", "Vila Belmiro", "Levir Culpi", ["Bruno Henrique"], [""]];
jogos.push(jogo92);
var jogo93 = ["Santos", "Vitória", 2, 2, "Campeonato Brasileiro", "2017-10-16", "Pacaembu", "Levir Culpi", ["Jean Mota","Ramon"], ["David","Wallace Reis"]];
jogos.push(jogo93);
var jogo94 = ["Santos", "Atlético-GO", 1, 0, "Campeonato Brasileiro", "2017-10-22", "Vila Belmiro", "Levir Culpi", ["Ricardo Oliveira"], [""]];
jogos.push(jogo94);
var jogo95 = ["Santos", "Atlético-MG", 3, 1, "Campeonato Brasileiro", "2017-11-04", "Vila Belmiro", "Levir Culpi", ["Arthur Gomes","David Braz","Ricardo Oliveira"], ["Fred"]];
jogos.push(jogo95);
var jogo96 = ["Santos", "Grêmio", 1, 0, "Campeonato Brasileiro", "2017-11-19", "Vila Belmiro", "Elano", ["Copete"], [""]];
jogos.push(jogo96);
var jogo97 = ["Flamengo", "Santos", 1, 2, "Campeonato Brasileiro", "2017-11-26", "Ilha do Urubu", "Elano", ["Bruno Henrique","Arthur Gomes"], ["Lucas Paquetá"]];
jogos.push(jogo97);
var jogo98 = ["Santos", "Avaí", 1, 1, "Campeonato Brasileiro", "2017-12-03", "Vila Belmiro", "Elano", ["Copete"], ["Pedro Castro"]];
jogos.push(jogo98);
var jogo99 = ["Santos", "Internacional", 1, 1, "Brasileirão de Aspirantes", "2017-12-10", "Vila Belmiro", "Kleiton Lima", ["Diego Cardoso"], ["Joanderson"]];
jogos.push(jogo99);
var jogo100 = ["Santos", "São Caetano", 2, 0, "Campeonato Paulista", "2018-02-14", "Vila Belmiro", "Jair Ventura", ["Lucas Veríssimo","Gabigol"], [""]];
jogos.push(jogo100);
var jogo101 = ["Santos", "Santo André", 2, 0, "Campeonato Paulista", "2018-02-25", "Vila Belmiro", "Jair Ventura", ["Gabigol","Eduardo Sasha"], [""]];
jogos.push(jogo101);
var jogo102 = ["Santos", "Corinthians", 1, 1, "Campeonato Paulista", "2018-03-04", "Pacaembu", "Jair Ventura", ["Diogo Vitor"], ["Renê Junior"]];
jogos.push(jogo102);
var jogo103 = ["Santos", "São Bento", 1, 3, "Campeonato Paulista", "2018-03-11", "Vila Belmiro", "Jair Ventura", ["Arthur Gomes"], ["Marcelo Cordeiro","Lúcio Flávio","Fábio Bahia"]];
jogos.push(jogo103);
var jogo104 = ["Santos", "Nacional-URU", 3, 1, "Copa Libertadores", "2018-03-15", "Pacaembu", "Jair Ventura", ["Eduardo Sasha (2x)","Rodrygo"], ["Oliva"]];
jogos.push(jogo104);
var jogo105 = ["Santos", "Botafogo-SP", 0, 0, "Campeonato Paulista", "2018-03-21", "Vila Belmiro", "Jair Ventura", ["","Pênaltis: (3)","Gabigol","Diogo Vitor","Arthur Gomes"], ["","Pênaltis: (1)","Jheymy"]];
jogos.push(jogo105);
var jogo106 = ["Santos", "Palmeiras", 0, 1, "Campeonato Paulista", "2018-03-24", "Pacaembu", "Jair Ventura", [""], ["Willian"]];
jogos.push(jogo106);
var jogo107 = ["Santos", "Ceará", 2, 0, "Campeonato Brasileiro", "2018-04-14", "Pacaembu", "Jair Ventura", ["Pio (GC)","Rodrygo"], [""]];
jogos.push(jogo107);
var jogo108 = ["Santos", "Estudiantes-ARG", 2, 0, "Copa Libertadores", "2018-04-24", "Vila Belmiro", "Jair Ventura", ["Gabigol","Lucas Veríssimo"], [""]];
jogos.push(jogo108);
var jogo183 = ["Nacional-URU", "Santos", 1, 0, "Copa Libertadores", "2018-05-01", "Gran Parque Central", "Jair Ventura", [""], ["Barcia"]];
jogos.push(jogo183);
var jogo109 = ["Santos", "Luverdense", 5, 1, "Copa do Brasil", "2018-05-10", "Vila Belmiro", "Jair Ventura", ["Gustavo Henrique","Gabigol (3x)","Yuri Alberto"], ["Itaqui"]];
jogos.push(jogo109);
var jogo110 = ["Santos", "Paraná", 3, 1, "Campeonato Brasileiro", "2018-05-13", "Vila Belmiro", "Jair Ventura", ["Gabigol (2x)","Rodrygo"], ["Silvinho"]];
jogos.push(jogo110);
var jogo111 = ["Santos", "Real Garcilaso-PER", 0, 0, "Copa Libertadores", "2018-05-24", "Vila Belmiro", "Jair Ventura", [""], [""]];
jogos.push(jogo111);
var jogo112 = ["Santos", "Cruzeiro", 0, 1, "Campeonato Brasileiro", "2018-05-27", "Pacaembu", "Jair Ventura", [""], ["Bruno Silva"]];
jogos.push(jogo112);
var jogo113 = ["Santos", "Vitória", 5, 2, "Campeonato Brasileiro", "2018-06-03", "Vila Belmiro", "Jair Ventura", ["Renato","Gabigol","Rodrygo(3x)"], ["Neílton","Ramon"]];
jogos.push(jogo113);
var jogo114 = ["Santos", "Internacional", 1, 2, "Campeonato Brasileiro", "2018-06-10", "Vila Belmiro", "Jair Ventura", ["Gabigol"], ["Leandro Damião","Victor Cuesta"]];
jogos.push(jogo114);
var jogo115 = ["Santos", "Palmeiras", 1, 1, "Campeonato Brasileiro", "2018-07-19", "Pacaembu", "Jair Ventura", ["Gustavo Henrique"], ["Lucas Lima"]];
jogos.push(jogo115);
var jogo116 = ["Santos", "Flamengo", 1, 1, "Campeonato Brasileiro", "2018-07-25", "Vila Belmiro", "Serginho Chulapa", ["Rodrygo"], ["Éverton Ribeiro"]];
jogos.push(jogo116);
var jogo117 = ["Santos", "América-MG", 0, 1, "Campeonato Brasileiro", "2018-07-29", "Vila Belmiro", "Serginho Chulapa", [""], ["Ruy"]];
jogos.push(jogo117);
var jogo118 = ["Santos", "Cruzeiro", 0, 1, "Copa do Brasil", "2018-08-01", "Vila Belmiro", "Cuca", [""], ["Raniel"]];
jogos.push(jogo118);
var jogo119 = ["Botafogo", "Santos", 0, 0, "Campeonato Brasileiro", "2018-08-04", "Nilton Santos", "Cuca", [""], [""]];
jogos.push(jogo119);
var jogo120 = ["Santos", "Sport", 3, 0, "Campeonato Brasileiro", "2018-08-18", "Vila Belmiro", "Cuca", ["Eduardo Sasha","Rodrygo","Victor Ferraz"], [""]];
jogos.push(jogo120);
var jogo121 = ["Independiente-ARG", "Santos", 0, 0, "Copa Libertadores", "2018-08-21", "Libertadores de América", "Cuca", [""], [""]];
jogos.push(jogo121);
var jogo122 = ["Santos", "Bahia", 2, 0, "Campeonato Brasileiro", "2018-08-25", "Vila Belmiro", "Cuca", ["Derlis González","Gabigol"], [""]];
jogos.push(jogo122);
var jogo123 = ["Santos", "Independiente-ARG", 0, 0, "Copa Libertadores", "2018-08-28", "Pacaembu", "Cuca", [""], [""]];
jogos.push(jogo123);
var jogo124 = ["Vasco", "Santos", 0, 3, "Campeonato Brasileiro", "2018-09-01", "Maracanã", "Cuca", ["Gabigol (3x)"], [""]];
jogos.push(jogo124);
var jogo125 = ["Santos", "Grêmio", 0, 0, "Campeonato Brasileiro", "2018-09-06", "Pacaembu", "Cuca", [""], [""]];
jogos.push(jogo125);
var jogo126 = ["Santos", "São Paulo", 0, 0, "Campeonato Brasileiro", "2018-09-16", "Vila Belmiro", "Cuca", [""], [""]];
jogos.push(jogo126);
var jogo127 = ["Santos", "Atlético-PR", 1, 0, "Campeonato Brasileiro", "2018-09-30", "Vila Belmiro", "Cuca", ["Carlos Sánchez"], [""]];
jogos.push(jogo127);
var jogo128 = ["Santos", "Corinthians", 1, 0, "Campeonato Brasileiro", "2018-10-13", "Pacaembu", "Cuca", ["Gabigol"], [""]];
jogos.push(jogo128);
var jogo129 = ["Santos", "Fluminense", 3, 0, "Campeonato Brasileiro", "2018-10-27", "Vila Belmiro", "Cuca", ["Gabigol","Carlos Sánchez","Victor Ferraz"], [""]];
jogos.push(jogo129);
var jogo130 = ["Santos", "Chapecoense", 0, 1, "Campeonato Brasileiro", "2018-11-12", "Pacaembu", "Cuca", [""], ["Leandro Pereira"]];
jogos.push(jogo130);
var jogo131 = ["Flamengo", "Santos", 1, 0, "Campeonato Brasileiro", "2018-11-15", "Maracanã", "Cuca", [""], ["Henrique Dourado"]];
jogos.push(jogo131);
var jogo132 = ["América-MG", "Santos", 2, 1, "Campeonato Brasileiro", "2018-11-18", "Arena Independência", "Cuca", ["Gabigol"], ["Rafael Moura","Matheusinho"]];
jogos.push(jogo132);
var jogo133 = ["Santos", "Botafogo", 1, 1, "Campeonato Brasileiro", "2018-11-21", "Vila Belmiro", "Cuca", ["Rodrygo"], ["Brenner"]];
jogos.push(jogo133);
var jogo134 = ["Santos", "Atlético-MG", 3, 2, "Campeonato Brasileiro", "2018-11-24", "Vila Belmiro", "Cuca", ["Felippe Cardoso","Gabigol","Carlos Sánchez"], ["Ricardo Oliveira (2x)"]];
jogos.push(jogo134);
var jogo135 = ["Sport", "Santos", 2, 1, "Campeonato Brasileiro", "2018-12-02", "Ilha do Retiro", "Cuca", ["Rodrygo"], ["Rogério","Hernane"]];
jogos.push(jogo135);
var jogo136 = ["Santos", "Ferroviária", 1, 0, "Campeonato Paulista", "2019-01-19", "Vila Belmiro", "Jorge Sampaoli", ["Jean Mota"], [""]];
jogos.push(jogo136);
var jogo137 = ["Santos", "São Paulo", 2, 0, "Campeonato Paulista", "2019-01-27", "Pacaembu", "Jorge Sampaoli", ["Luiz Felipe","Derlis González"], [""]];
jogos.push(jogo137);
var jogo138 = ["Ituano", "Santos", 5, 1, "Campeonato Paulista", "2019-02-03", "Municipal Doutor Novelli Júnior", "Jorge Sampaoli", ["Jean Mota"], ["Marcos Serato","Morato (2x)","Léo Santos","Jonas"]];
jogos.push(jogo138);
var jogo139 = ["Santos", "Mirassol", 1, 0, "Campeonato Paulista", "2019-02-09", "Pacaembu", "Jorge Sampaoli", ["Jean Mota"], [""]];
jogos.push(jogo139);
var jogo140 = ["River Plate-URU", "Santos", 0, 0, "Copa Sul-Americana", "2019-02-12", "Luis Franzini", "Jorge Sampaoli", [""], [""]];
jogos.push(jogo140);
var jogo141 = ["Santos", "Guarani", 3, 0, "Campeonato Paulista", "2019-02-18", "Pacaembu", "Jorge Sampaoli", ["Rodrygo","Jean Mota (2x)"], [""]];
jogos.push(jogo141);
var jogo142 = ["Santos", "Oeste", 3, 2, "Campeonato Paulista", "2019-03-02", "Pacaembu", "Jorge Sampaoli", ["Betinho (GC)","Derlis González","Victor Ferraz"], ["Bruno Lopes","Matheus Jesus"]];
jogos.push(jogo142);
var jogo143 = ["Santos", "América-RN", 4, 0, "Copa do Brasil", "2019-03-09", "Pacaembu", "Jorge Sampaoli", ["Rodrygo","Aguilar","Jean Mota","Derlis González"], [""]];
jogos.push(jogo143);
var jogo144 = ["Santos", "Novorizontino", 0, 1, "Campeonato Paulista", "2019-03-15", "Pacaembu", "Jorge Sampaoli", [""], ["Murilo Henrique"]];
jogos.push(jogo144);
var jogo145 = ["Santos", "Red Bull Brasil", 2, 0, "Campeonato Paulista", "2019-03-23", "Pacaembu", "Jorge Sampaoli", ["Diego Pituca","Carlos Sánchez"], [""]];
jogos.push(jogo145);
var jogo146 = ["Santos", "Corinthians", 1, 0, "Campeonato Paulista", "2019-04-08", "Pacaembu", "Jorge Sampaoli", ["Gustavo Henrique","","Pênaltis: (6)","Rodrygo","Soteldo","Carlos Sánchez","Derlis González","Diego Pituca","Alison"], ["","","Pênaltis: (7)","Vagner Love","Ramiro","Júnior Urso","Fagner","Sornoza","Danilo Avelar","Henrique"]];
jogos.push(jogo146);
var jogo147 = ["Santos", "Vasco", 2, 0, "Copa do Brasil", "2019-04-17", "Vila Belmiro", "Jorge Sampaoli", ["Rodrygo","Jean Mota"], [""]];
jogos.push(jogo147);
var jogo148 = ["Grêmio", "Santos", 1, 2, "Campeonato Brasileiro", "2019-04-28", "Arena do Grêmio", "Jorge Sampaoli", ["Eduardo Sasha","Felipe Jonathan"], ["Éverton"]];
jogos.push(jogo148);
var jogo149 = ["Santos", "Vasco", 3, 0, "Campeonato Brasileiro", "2019-05-12", "Pacaembu", "Jorge Sampaoli", ["Diego Pituca","Rodrygo","Soteldo"], [""]];
jogos.push(jogo149);
var jogo150 = ["Santos", "Internacional", 0, 0, "Campeonato Brasileiro", "2019-05-26", "Vila Belmiro", "Jorge Sampaoli", [""], [""]];
jogos.push(jogo150);
var jogo151 = ["Ceará", "Santos", 0, 1, "Campeonato Brasileiro", "2019-06-02", "Castelão", "Jorge Sampaoli", ["Eduardo Sasha"], [""]];
jogos.push(jogo151);
var jogo152 = ["Juventus", "Santos", 1, 8, "Campeonato Paulista (Feminino)", "2019-06-08", "Conde Rodolfo Crespi (Rua Javari)", "Emily Lima", ["Maria Dias","Maria Alves","Sandrinha","Sochor","Glaucia","Katielle","Ketlen (2x)"], ["Dani"]];
jogos.push(jogo152);
var jogo153 = ["Santos", "Atlético-MG", 3, 1, "Campeonato Brasileiro", "2019-06-09", "Vila Belmiro", "Jorge Sampaoli", ["Eduardo Sasha","Jean Mota","Carlos Sánchez"], ["Alerrandro"]];
jogos.push(jogo153);
var jogo154 = ["Santos", "Corinthians", 1, 0, "Campeonato Brasileiro", "2019-06-12", "Vila Belmiro", "Jorge Sampaoli", ["Eduardo Sasha"], [""]];
jogos.push(jogo154);
var jogo155 = ["Bahia", "Santos", 0, 1, "Campeonato Brasileiro", "2019-07-13", "Pituaçu", "Jorge Sampaoli", ["Carlos Sánchez"], [""]];
jogos.push(jogo155);
var jogo156 = ["Botafogo", "Santos", 0, 1, "Campeonato Brasileiro", "2019-07-21", "Nilton Santos", "Jorge Sampaoli", ["Marinho"], [""]];
jogos.push(jogo156);
var jogo157 = ["Santos", "Avaí", 3, 1, "Campeonato Brasileiro", "2019-07-28", "Vila Belmiro", "Jorge Sampaoli", ["Felipe Jonathan","Carlos Sánchez","Derlis González"], ["João Paulo"]];
jogos.push(jogo157);
var jogo158 = ["Santos", "Goiás", 6, 1, "Campeonato Brasileiro", "2019-08-04", "Vila Belmiro", "Jorge Sampaoli", ["Lucas Veríssimo","Soteldo (2x)","Carlos Sánchez","Gustavo Henrique","Eduardo Sasha"], ["Kayke"]];
jogos.push(jogo158);
var jogo159 = ["Cruzeiro", "Santos", 2, 0, "Campeonato Brasileiro", "2019-08-18", "Mineirão", "Jorge Sampaoli", [""], ["Fred","Thiago Neves"]];
jogos.push(jogo159);
var jogo160 = ["Santos", "Fortaleza", 3, 3, "Campeonato Brasileiro", "2019-08-25", "Vila Belmiro", "Jorge Sampaoli", ["Jorge","Eduardo Sasha","Marinho"], ["Wellington Paulista (2x)","Tinga"]];
jogos.push(jogo160);
var jogo161 = ["Santos", "Athletico-PR", 1, 1, "Campeonato Brasileiro", "2019-09-08", "Vila Belmiro", "Jorge Sampaoli", ["Carlos Sánchez"], ["Braian Romero"]];
jogos.push(jogo161);
var jogo162 = ["Flamengo", "Santos", 1, 0, "Campeonato Brasileiro", "2019-09-14", "Maracanã", "Jorge Sampaoli", [""], ["Gabriel"]];
jogos.push(jogo162);
var jogo163 = ["Santos", "São Paulo", 2, 2, "Campeonato Paulista (Feminino)", "2019-09-21", "Pacaembu", "Guilherme Giudice", ["Sole Jaimes","Ketlen"], ["Thaís","Natane"]];
jogos.push(jogo163);
var jogo164 = ["Santos", "Grêmio", 0, 3, "Campeonato Brasileiro", "2019-09-21", "Vila Belmiro", "Jorge Sampaoli", [""], ["Luan","Pepê","Éverton"]];
jogos.push(jogo164);
var jogo165 = ["Santos", "CSA", 2, 0, "Campeonato Brasileiro", "2019-09-29", "Vila Belmiro", "Jorge Sampaoli", ["Carlos Sánchez","Eduardo Sasha"], [""]];
jogos.push(jogo165);
var jogo166 = ["Vasco", "Santos", 0, 1, "Campeonato Brasileiro", "2019-10-05", "São Januário", "Jorge Sampaoli", ["Tailson"], [""]];
jogos.push(jogo166);
var jogo167 = ["Santos", "Palmeiras", 2, 0, "Campeonato Brasileiro", "2019-10-09", "Vila Belmiro", "Jorge Sampaoli", ["Gustavo Henrique","Marinho"], [""]];
jogos.push(jogo167);
var jogo168 = ["Internacional", "Santos", 0, 0, "Campeonato Brasileiro", "2019-10-13", "Beira-Rio", "Jorge Sampaoli", [""], [""]];
jogos.push(jogo168);
var jogo169 = ["Atlético-MG", "Santos", 2, 0, "Campeonato Brasileiro", "2019-10-20", "Arena Independência", "Jorge Sampaoli", [""], ["Leonardo Silva","Luan"]];
jogos.push(jogo169);
var jogo170 = ["Santos", "Botafogo", 4, 1, "Campeonato Brasileiro", "2019-11-03", "Vila Belmiro", "Jorge Sampaoli", ["Eduardo Sasha","Marinho","Soteldo (2x)"], ["Igor Cássio"]];
jogos.push(jogo170);
var jogo171 = ["Goiás", "Santos", 0, 3, "Campeonato Brasileiro", "2019-11-09", "Serra Dourada", "Jorge Sampaoli", ["Soteldo (2x)","Marinho"], [""]];
jogos.push(jogo171);
var jogo172 = ["Santos", "São Paulo", 1, 1, "Campeonato Brasileiro", "2019-11-16", "Vila Belmiro", "Jorge Sampaoli", ["Carlos Sánchez"], ["Daniel Alves"]];
jogos.push(jogo172);
var jogo173 = ["Santos", "Cruzeiro", 4, 1, "Campeonato Brasileiro", "2019-11-23", "Vila Belmiro", "Jorge Sampaoli", ["Eduardo Sasha","Marinho","Soteldo","Diego Pituca"], ["Orejuela"]];
jogos.push(jogo173);
var jogo174 = ["Santos", "Chapecoense", 2, 0, "Campeonato Brasileiro", "2019-12-01", "Vila Belmiro", "Jorge Sampaoli", ["Lucas Veríssimo","Evandro"], [""]];
jogos.push(jogo174);
var jogo175 = ["Santos", "Flamengo", 4, 0, "Campeonato Brasileiro", "2019-12-08", "Vila Belmiro", "Jorge Sampaoli", ["Marinho","Carlos Sánchez (2x)","Eduardo Sasha"], [""]];
jogos.push(jogo175);
var jogo176 = ["Santos", "Red Bull Bragantino", 0, 0, "Campeonato Paulista", "2020-01-23", "Vila Belmiro", "Jesualdo Ferreira", [""], [""]];
jogos.push(jogo176);
var jogo177 = ["Santos", "Botafogo-SP", 2, 0, "Campeonato Paulista", "2020-02-10", "Vila Belmiro", "Jesualdo Ferreira", ["Carlos Sánchez","Eduardo Sasha"], [""]];
jogos.push(jogo177);
var jogo178 = ["Ferroviária", "Santos", 0, 0, "Campeonato Paulista", "2020-02-16", "Fonte Luminosa", "Jesualdo Ferreira", [""], [""]];
jogos.push(jogo178);
var jogo179 = ["Ituano", "Santos", 2, 0, "Campeonato Paulista", "2020-02-22", "Municipal Doutor Novelli Júnior", "Jesualdo Ferreira", [""], ["Yago","Corrêa"]];
jogos.push(jogo179);
var jogo180 = ["Santos", "Palmeiras", 0, 0, "Campeonato Paulista", "2020-02-29", "Pacaembu", "Jesualdo Ferreira", [""], [""]];
jogos.push(jogo180);
var jogo181 = ["Defensa y Justicia-ARG", "Santos", 1, 2, "Copa Libertadores", "2020-03-03", "Norberto 'Tito' Tomaghello", "Jesualdo Ferreira", ["Jobson","Kaio Jorge"], ["Juan Rodríguez"]];
jogos.push(jogo181);
var jogo20200307 = ["Santos", "Mirassol", 3, 1, "Campeonato Paulista", "2020-03-07", "Vila Belmiro", "Jesualdo Ferreira", ["Yuri Alberto","Diego Pituca","Eduardo Sasha"], ["Rafael Silva"]];
jogos.push(jogo20200307);
var jogo20210130 = ["Palmeiras", "Santos", 1, 0, "Copa Libertadores", "2021-01-30", "Maracanã", "Cuca", [""], ["Breno Lopes"]];
jogos.push(jogo20210130);
var jogo20210822 = ["Santos", "Internacional", 2, 2, "Campeonato Brasileiro", "2021-08-22", "Vila Belmiro", "Fernando Diniz", ["Gabriel Pirani","Madson"], ["Gabriel Mercado","Yuri Alberto"]];
jogos.push(jogo20210822);
var jogo20211010 = ["Santos", "Grêmio", 1, 0, "Campeonato Brasileiro", "2021-10-10", "Vila Belmiro", "Fábio Carille", ["Wagner Leonardo"], [""]];
jogos.push(jogo20211010);
var jogo20211023 = ["Santos", "América-MG", 0, 2, "Campeonato Brasileiro", "2021-10-23", "Vila Belmiro", "Fábio Carille", [""], ["Ademir","Alê"]];
jogos.push(jogo20211023);
var jogo20211107 = ["Santos", "Palmeiras", 0, 2, "Campeonato Brasileiro", "2021-11-07", "Vila Belmiro", "Fábio Carille", [""], ["Rony","Rafael Veiga"]];
jogos.push(jogo20211107);
var jogo20211110 = ["Santos", "Red Bull Bragantino", 2, 0, "Campeonato Brasileiro", "2021-11-10", "Vila Belmiro", "Fábio Carille", ["Marinho","Carlos Sánchez"], [""]];
jogos.push(jogo20211110);